version: '3.8'
services:

  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    network_mode: bridge
    ports:
      - 80:80
      - 443:443
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - dhparam:/etc/nginx/dhparam
      - certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    healthcheck:
      test: ["CMD", "true"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-proxy-le
    network_mode: bridge
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
      - DEFAULT_EMAIL=wechaty@chatie.io
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - dhparam:/etc/nginx/dhparam
      - certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    network_mode: bridge
    expose:
      - 8080
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_HTTP_API_TOKEN=lizhuohuan
      - VIRTUAL_HOST=watchtower.chatie.io
      - LETSENCRYPT_HOST=watchtower.chatie.io
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      - --debug
      - --http-api
      - friday

  localtunnel:
    image: defunctzombie/localtunnel-server
    container_name: localtunnel
    network_mode: host
    command:
      - --port
      - '3000'
      - --domain
      - localtunnel.chatie.io

  watchdog:
    image: chatie/watchdog.icu
    container_name: watchdog.icu
    network_mode: bridge
    environment:
      - VIRTUAL_HOST=watchdog.icu,www.watchdog.icu
      - LETSENCRYPT_HOST=watchdog.icu,www.watchdog.icu

volumes:
  conf:
  vhost:
  html:
  dhparam:
  certs:
